export const PERMISSION_SEEDS = [
    {
        name: 'Ver panel principal',
        code: 'dashboard.view',
        module: 'General',
        resource: 'dashboard',
        action: 'view',
        description: 'Consultar indicadores y accesos del panel principal.',
    },
    {
        name: 'Gestión total del sistema',
        code: 'system.manage',
        module: 'Seguridad',
        resource: 'system',
        action: 'manage',
        description: 'Administrar todas las funciones y configuraciones del sistema.',
    },
    {
        name: 'Consultar usuarios',
        code: 'users.view',
        module: 'Seguridad',
        resource: 'users',
        action: 'view',
        description: 'Consultar las cuentas de acceso vinculadas a miembros.',
    },
    {
        name: 'Crear usuarios',
        code: 'users.create',
        module: 'Seguridad',
        resource: 'users',
        action: 'create',
        description: 'Crear cuentas de acceso para miembros de la comunidad.',
    },
    {
        name: 'Modificar usuarios',
        code: 'users.update',
        module: 'Seguridad',
        resource: 'users',
        action: 'update',
        description: 'Modificar credenciales, roles y opciones de seguridad.',
    },
    {
        name: 'Bloquear usuarios',
        code: 'users.block',
        module: 'Seguridad',
        resource: 'users',
        action: 'block',
        description: 'Bloquear o habilitar el acceso de un usuario.',
    },
    {
        name: 'Consultar miembros',
        code: 'members.view',
        module: 'Comunidad',
        resource: 'members',
        action: 'view',
        description: 'Consultar el directorio y el detalle de miembros.',
    },
    {
        name: 'Crear miembros',
        code: 'members.create',
        module: 'Comunidad',
        resource: 'members',
        action: 'create',
        description: 'Registrar miembros en el directorio de la comunidad.',
    },
    {
        name: 'Modificar miembros',
        code: 'members.update',
        module: 'Comunidad',
        resource: 'members',
        action: 'update',
        description: 'Actualizar la información personal y pastoral de miembros.',
    },
    {
        name: 'Importar y exportar miembros',
        code: 'members.import_export',
        module: 'Comunidad',
        resource: 'members',
        action: 'export',
        description: 'Importar y exportar información de miembros mediante Excel.',
    },
    {
        name: 'Consultar roles',
        code: 'roles.view',
        module: 'Seguridad',
        resource: 'roles',
        action: 'view',
        description: 'Consultar roles y sus permisos asignados.',
    },
    {
        name: 'Administrar roles',
        code: 'roles.manage',
        module: 'Seguridad',
        resource: 'roles',
        action: 'manage',
        description: 'Crear, modificar y desactivar roles del sistema.',
    },
    {
        name: 'Consultar permisos',
        code: 'permissions.view',
        module: 'Seguridad',
        resource: 'permissions',
        action: 'view',
        description: 'Consultar el catálogo de permisos del sistema.',
    },
    {
        name: 'Administrar permisos',
        code: 'permissions.manage',
        module: 'Seguridad',
        resource: 'permissions',
        action: 'manage',
        description: 'Crear, modificar y desactivar permisos del sistema.',
    },
    {
        name: 'Consultar reuniones',
        code: 'meetings.view',
        module: 'Catálogos',
        resource: 'meetings',
        action: 'view',
        description: 'Consultar reuniones programadas y su detalle.',
    },
    {
        name: 'Administrar reuniones',
        code: 'meetings.manage',
        module: 'Catálogos',
        resource: 'meetings',
        action: 'manage',
        description: 'Crear, modificar y cancelar reuniones.',
    },
    {
        name: 'Consultar territorios',
        code: 'territories.view',
        module: 'Catálogos',
        resource: 'territories',
        action: 'view',
        description: 'Consultar distritos, zonas, sectores y cobertura territorial.',
    },
    {
        name: 'Administrar territorios',
        code: 'territories.manage',
        module: 'Catálogos',
        resource: 'territories',
        action: 'manage',
        description: 'Crear y modificar distritos, zonas y sectores.',
    },
    {
        name: 'Consultar finanzas',
        code: 'finance.view',
        module: 'Finanzas',
        resource: 'finance',
        action: 'view',
        description: 'Consultar movimientos y resúmenes financieros.',
    },
    {
        name: 'Registrar ofrendas',
        code: 'finance.record',
        module: 'Finanzas',
        resource: 'finance',
        action: 'record',
        description: 'Registrar asistencia y ofrendas de las reuniones a su cargo.',
    },
    {
        name: 'Administrar finanzas',
        code: 'finance.manage',
        module: 'Finanzas',
        resource: 'finance',
        action: 'manage',
        description: 'Corregir o eliminar registros de ofrenda ya capturados.',
    },
    {
        name: 'Exportar reportes',
        code: 'reports.export',
        module: 'Reportes',
        resource: 'reports',
        action: 'export',
        description: 'Generar y descargar reportes del sistema.',
    },
    {
        name: 'Consultar auditoría',
        code: 'audit.view',
        module: 'Seguridad',
        resource: 'audit',
        action: 'view',
        description: 'Consultar la bitácora de actividad y seguridad.',
    },
]

export function seedPermissions(prisma) {
    return prisma.$transaction(
        PERMISSION_SEEDS.map((permission) =>
            prisma.permission.upsert({
                where: { code: permission.code },
                create: {
                    ...permission,
                    isSystem: true,
                    status: 'ACTIVE',
                },
                update: {
                    ...permission,
                    isSystem: true,
                    status: 'ACTIVE',
                },
            }),
        ),
    )
}
